package main

import (
	"crypto/ecdh"
	"encoding/base64"
	"encoding/hex"
	"testing"

	"filippo.io/edwards25519"
)

// ecdhX25519NewPrivateKey mirrors the production key load (p2p_noise.go);
// declared here so the vector test builds a key from raw scalar bytes.
func ecdhX25519NewPrivateKey(k []byte) (*ecdh.PrivateKey, error) {
	return ecdh.X25519().NewPrivateKey(k)
}

// TestReqSigRoundtrip: a signature made with an identity key verifies
// against that key's X25519 public key (the roster anchor), and fails
// against any other key (the impersonation case).
func TestReqSigRoundtrip(t *testing.T) {
	id, err := generateIdentity()
	if err != nil {
		t.Fatal(err)
	}
	pub := id.publicKey()
	msg := []byte("POST|/api/v1/session/123456/heartbeat|1720000000000|deadbeef")
	sig, err := signWithIdentity(id, msg)
	if err != nil {
		t.Fatal(err)
	}
	if len(sig) != 64 {
		t.Fatalf("sig length = %d; want 64", len(sig))
	}
	if !verifyRequestSigAgainstX25519(pub, msg, sig) {
		t.Fatal("signature must verify against the identity's own pubkey")
	}
	other, _ := generateIdentity()
	if verifyRequestSigAgainstX25519(other.publicKey(), msg, sig) {
		t.Fatal("signature must NOT verify against a different pubkey")
	}
	// Tampered message (different path = different request) must fail.
	if verifyRequestSigAgainstX25519(pub, []byte("POST|/api/v1/session/123456/kick|1720000000000|deadbeef"), sig) {
		t.Fatal("signature must not verify a tampered message")
	}
}

// TestReqSigMontgomeryConsistency proves the core identity of the scheme:
// the Edwards point A = a·B derived from the X25519 scalar has a Montgomery
// u-coordinate EXACTLY equal to the X25519 public key, and its compressed
// form has sign bit 0 (what the server derives from the pubkey alone).
func TestReqSigMontgomeryConsistency(t *testing.T) {
	for i := 0; i < 5; i++ {
		id, err := generateIdentity()
		if err != nil {
			t.Fatal(err)
		}
		k := append([]byte{}, id.priv.Bytes()...)
		k[0] &= 248 // clamp like X25519 (ecdh raw scalars are unclamped)
		k[31] &= 127
		k[31] |= 64
		var buf [64]byte
		copy(buf[:32], k)
		a, err := edwards25519.NewScalar().SetUniformBytes(buf[:])
		if err != nil {
			t.Fatal(err)
		}
		A := edwards25519.NewGeneratorPoint().ScalarBaseMult(a)
		if A.Bytes()[31]&0x80 == 0x80 {
			A.Negate(A)
		}
		if got := A.BytesMontgomery(); hex.EncodeToString(got) != hex.EncodeToString(id.publicKey()) {
			t.Fatalf("mont(A) = %x; want X25519 pubkey %x", got, id.publicKey())
		}
		if A.Bytes()[31]&0x80 != 0 {
			t.Fatal("compressed A must have sign bit 0")
		}
		// And the server-side derivation from the pubkey recovers A.
		derived, err := x25519PubkeyToEdwards(id.publicKey())
		if err != nil {
			t.Fatal(err)
		}
		if hex.EncodeToString(derived) != hex.EncodeToString(A.Bytes()) {
			t.Fatalf("derived A = %x; want %x", derived, A.Bytes())
		}
	}
}

// TestReqSigFixedVector pins a cross-language vector: the TS verifier
// (src/lib) must accept THIS signature, generated by the Go signer.
func TestReqSigFixedVector(t *testing.T) {
	// Fixed key: clamped 0x01...01 scalar — deterministic across runs.
	// (X25519 private scalars must be clamped before use, same as the
	// persisted identity file's bytes.)
	k, err := hex.DecodeString("0101010101010101010101010101010101010101010101010101010101010101")
	if err != nil {
		t.Fatal(err)
	}
	k[0] &= 248
	k[31] &= 127
	k[31] |= 64
	priv, err := ecdhX25519NewPrivateKey(k)
	if err != nil {
		t.Fatal(err)
	}
	id := &identityKey{priv: priv, pub: priv.PublicKey().Bytes()}
	msg := []byte("POST|/api/v1/session/123456/heartbeat|1720000000000|00112233445566778899aabbccddeeff")
	sig, err := signWithIdentity(id, msg)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("pubkey-b64: %s", base64.StdEncoding.EncodeToString(id.publicKey()))
	t.Logf("signature-b64: %s", base64.StdEncoding.EncodeToString(sig))
	if !verifyRequestSigAgainstX25519(id.publicKey(), msg, sig) {
		t.Fatal("fixed vector must self-verify")
	}
}

// TestReqSigRejectsGarbagePubkeys: malformed anchors never verify.
func TestReqSigRejectsGarbagePubkeys(t *testing.T) {
	id, _ := generateIdentity()
	msg := []byte("GET|/x|1|2")
	sig, _ := signWithIdentity(id, msg)
	if verifyRequestSigAgainstX25519(make([]byte, 32), msg, sig) {
		t.Fatal("all-zero pubkey must not verify")
	}
	// u = p-1 (the point at infinity on the edwards side) must be rejected.
	pminus1 := make([]byte, 32)
	pminus1[0] = 0xec
	pminus1[31] = 0x7f
	if verifyRequestSigAgainstX25519(pminus1, msg, sig) {
		t.Fatal("u = p-1 must not verify")
	}
	if verifyRequestSigAgainstX25519(id.publicKey(), msg, sig[:32]) {
		t.Fatal("truncated signature must not verify")
	}
}